IF DB_ID('MYDATABASE') IS NULL
CREATE DATABASE MYDATABASE
USE MASTER 
ALTER DATABASE MYDATABASE SET SINGLE_USER;
ALTER DATABASE MYDATABASE COLLATE LATIN1_GENERAL_100_CI_AI
ALTER DATABASE MYDATABASE COLLATE ARABIC_CI_AS;   --Add Collate Arabic language
ALTER DATABASE MYDATABASE SET MULTI_USER;
GO
USE MYDATABASE
GO
------------------------------
------------------------------

------Creation Tables

-- Table Items
CREATE TABLE [MYDATABASE].[DBO].[ITEMS](

ID 						INT NOT NULL IDENTITY(1,1),
ITEM_NUMBER 			INT NULL,
ITEM_CODE 				VARCHAR(MAX) NULL,
ITEM_NAME 				VARCHAR(MAX) NULL,
ITEM_CONSUMER_PRICE 	FLOAT(53) NULL,
CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC)
);
GO
-- Table Customers
CREATE TABLE [MYDATABASE].[DBO].[CUSTOMERS](
ID 						INT NOT NULL IDENTITY(1,1),
CUSTOMER_SERIAL 		INT NULL,
CUSTOMER_FIRST_NAME 	VARCHAR(MAX) NULL, 
CUSTOMER_SECOUND_NAME 	VARCHAR(MAX) NULL,
CUSTOMER_LAST_NAME 		VARCHAR(MAX) NULL,
CUSTOMER_CIVIL_ID 		VARCHAR(MAX) NULL,
CUSTOMER_PHONE_NUMBER 	VARCHAR(MAX) NULL
CONSTRAINT PK_CUSTOMERS PRIMARY KEY CLUSTERED (ID ASC)
);
GO
-- Table Suppliers
CREATE TABLE [MYDATABASE].[DBO].[SUPPLIERS](
ID INT NOT NULL IDENTITY(1,1),
SUPPLIER_SERIAL INT NULL,
SUPPLIER_NAME VARCHAR(MAX) NULL,
SUPPLIER_PHONE_NUMBER VARCHAR(MAX) NULL,
CONSTRAINT PK_SUPPLIERS PRIMARY KEY CLUSTERED (ID ASC)
);
GO

------Creation StoreProcedure
--StoreProcedure Items
CREATE PROC [DBO].[ITEM_MAX_NUMBER]
AS
SELECT MAX(ITEM_NUMBER) FROM ITEMS
GO
--StoreProcedure Customers
CREATE PROC [DBO].[CUSTOMER_MAX_SERIAL]
AS
SELECT MAX(CUSTOMER_SERIAL) FROM CUSTOMERS
GO
--StoreProcedure SUPPLIERS
CREATE PROC [DBO].[SUPPLIERS_MAX_SERIAL]
AS
SELECT MAX(SUPPLIER_SERIAL) FROM SUPPLIERS
GO



